sudo: required
services:
  - docker

# Build test image of client project and run tests
before_install:
  - docker build -t rhysgoehring/react-test -f ./client/Dockerfile.dev ./client

# Now that we built the test image we need to use it to run tests
script:
  - docker run rhysgoehring/react-test npm test -- --coverage

# After tests pass, build production docker images:
after_success:
  - docker build -t rhysgoehring/multi-client ./client
  - docker build -t rhysgoehring/multi-nginx ./nginx
  - docker build -t rhysgoehring/multi-server ./server
  - docker build -t rhysgoehring/multi-worker ./worker

  # 1. Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # 2. Take our production images and push them to docker hub
  - docker push rhysgoehring/multi-client
  - docker push rhysgoehring/multi-nginx
  - docker push rhysgoehring/multi-server
  - docker push rhysgoehring/multi-worker

# Travis Deploy Script
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-529212055338
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    